# Generated by Django 5.0.4 on 2024-07-01 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tclone', '0006_bolt_delete_tweet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bolt',
            name='likes',
            field=models.ManyToManyField(related_name='BoltLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
