# Generated by Django 5.0.4 on 2024-07-04 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tclone', '0009_sharedbolt_delete_sharedbolts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sharedbolt',
            name='bolt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tclone.bolt'),
        ),
        migrations.AlterField(
            model_name='sharedbolt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
